kind: PersistentVolume
apiVersion: v1
metadata:
  name: microclimate-pv
  labels:
    type: local-storage
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/export/ICP3/microclimate"
    server: 192.168.24.33
